name: code analysis & format

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2.3.0
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: flutter format -n --set-exit-if-changed .
      - name: Linter
        run: flutter analyze